use db_ptp;
SET FOREIGN_KEY_CHECKS = 0;
truncate class;
ALTER TABLE class AUTO_INCREMENT=1;
truncate course;
ALTER TABLE course AUTO_INCREMENT=1;
truncate examinations;
ALTER TABLE examinations AUTO_INCREMENT=1;
truncate examscore;
ALTER TABLE examscore AUTO_INCREMENT=1;
truncate examsub;
ALTER TABLE examsub AUTO_INCREMENT=1;
truncate excises;
ALTER TABLE excises AUTO_INCREMENT=1;
truncate exinfor;
ALTER TABLE exinfor AUTO_INCREMENT=1;
truncate lang;
ALTER TABLE lang AUTO_INCREMENT=1;
truncate logs;
ALTER TABLE logs AUTO_INCREMENT=1;
truncate news;
ALTER TABLE news AUTO_INCREMENT=1;
truncate power;
ALTER TABLE power AUTO_INCREMENT=1;
truncate student;
ALTER TABLE student AUTO_INCREMENT=1;
truncate subjects;
ALTER TABLE subjects AUTO_INCREMENT=1;
truncate submits;
ALTER TABLE submits AUTO_INCREMENT=1;
truncate teacher;
ALTER TABLE teacher AUTO_INCREMENT=1;
truncate testsets;
ALTER TABLE testsets AUTO_INCREMENT=1;
SET FOREIGN_KEY_CHECKS = 1;